name: get_loading
description: A light-weight loading/toast widget for Flutter, based on get_module
version: 0.1.0
homepage: https://github.com/rua-flutter/get_module.dart/tree/main/get_loading

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: '>=4.0.0 <5.0.0'
  get_module:
    path: '../get_module'
  get_event_bus: '>=1.0.0 <2.0.0'
  flutter_easyloading: '>=3.0.0 <4.0.0'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
