name: get_module
description: A minimal and scalable light-weight module loader library for get.dart
version: 0.2.0
homepage: https://github.com/rua-flutter/get_module.dart

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: '>=4.0.0 <5.0.0'
  get_event_bus: '>=1.0.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
